# Generated by Django 4.0.6 on 2022-07-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-time_posted']},
        ),
        migrations.AlterModelOptions(
            name='discussionforum',
            options={'ordering': ['-is_pinned', '-time_posted']},
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Communications.discussionforum'),
        ),
    ]
