# Generated by Django 4.0.6 on 2022-07-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-year', '-sem', 'subject', 'course_code']},
        ),
    ]
