# Generated by Django 4.0.6 on 2022-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'ordering': ['course'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('1', 'Ongoing'), ('2', 'Completed')], default='1', max_length=1),
        ),
    ]
