# Generated by Django 4.0.6 on 2022-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_participants_options_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
