# Generated by Django 4.0.6 on 2022-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_participants_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
