# Generated by Django 4.0.6 on 2022-07-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignemet_name',
            new_name='assignment_name',
        ),
    ]
