# Generated by Django 4.0.6 on 2022-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_rename_assignemet_name_assignment_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
