# Generated by Django 4.0.6 on 2022-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_alter_assignmentsubmission_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='assignment_resources/'),
        ),
    ]
