# Generated by Django 4.0.6 on 2022-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_assignment_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resource_display_name',
            field=models.TextField(blank=True, default='Resources', null=True),
        ),
    ]
