# Generated by Django 4.0.6 on 2022-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0005_assignment_resource_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='resource_display_name',
            field=models.CharField(blank=True, default='Resources', max_length=100, null=True),
        ),
    ]
