# Generated by Django 4.0.6 on 2022-07-27 10:23

import Grades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0006_alter_assignment_resource_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to=Grades.models.Assignment.file_upload_path),
        ),
    ]
