# Generated by Django 4.0.6 on 2022-07-27 10:32

import Grades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_alter_assignment_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Grades.models.AssignmentSubmission.file_upload_path),
        ),
    ]
