# Generated by Django 4.0.6 on 2022-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0008_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='graded_manually',
            field=models.BooleanField(default=False),
        ),
    ]
