# Generated by Django 4.0.6 on 2022-07-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0009_grade_graded_manually'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='graded_manually',
        ),
    ]
