# Generated by Django 4.0.6 on 2022-07-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Doc', 'verbose_name_plural': 'Docs'},
        ),
    ]
