# Generated by Django 4.0.6 on 2022-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_alter_docs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
